// BMW E60 Coder Pro - Complete Engine Database
import type { EngineSpecs, InjectorSpec, DmeFlashProtocol } from '@/types';

export const ENGINE_SPECS: Record<string, EngineSpecs> = {
  n54: {
    code: 'n54',
    name: 'N54',
    fullName: 'N54B30 (Twin-Turbo Inline-6)',
    displacement: 3.0,
    cylinders: 6,
    fuelType: 'gasoline',
    aspiration: 'twin_turbo',
    stockPower: 306,
    stockTorque: 400,
    stockBoost: 0.6,
    redline: 7000,
    revLimit: 7200,
    compressionRatio: 10.2,
    bore: 84.0,
    stroke: 89.6,
    hasVanos: true,
    hasValvetronic: true,
    hasDirectInjection: true,
    ecuType: 'MED17.2',
    dmeFamily: 'MSD80/MSD81',
    supportedMaps: ['stock', 'stage1', 'stage2', 'stage2plus', 'stage3', 'custom', 'economy', 'valet', 'anti_theft'],
    maxSafeBoost: 1.8,
    maxSafePower: 700,
    injectorSizeCc: 630,
    fuelPumpType: 'Bosch low-pressure + high-pressure mechanical',
    commonIssues: ['Turbo wastegate rattle', 'High-pressure fuel pump failure', 'Carbon buildup on intake valves', 'Oil filter housing gasket leak', 'Chargepipe failure under boost'],
  },
  n52: {
    code: 'n52',
    name: 'N52',
    fullName: 'N52B30 (Naturally Aspirated Inline-6)',
    displacement: 3.0,
    cylinders: 6,
    fuelType: 'gasoline',
    aspiration: 'naturally_aspirated',
    stockPower: 258,
    stockTorque: 300,
    redline: 7000,
    revLimit: 7200,
    compressionRatio: 10.7,
    bore: 85.0,
    stroke: 88.0,
    hasVanos: true,
    hasValvetronic: true,
    hasDirectInjection: false,
    ecuType: 'ME9.2',
    dmeFamily: 'MEV17.2',
    supportedMaps: ['stock', 'stage1', 'custom', 'economy', 'valet', 'anti_theft'],
    maxSafePower: 300,
    injectorSizeCc: 380,
    fuelPumpType: 'Bosch in-tank',
    commonIssues: ['Valvetronic motor failure', 'Oil consumption (piston rings)', 'DISA valve failure', 'Electric water pump failure', 'VANOS solenoid seal leak'],
  },
  m54: {
    code: 'm54',
    name: 'M54',
    fullName: 'M54B30 (Naturally Aspirated Inline-6)',
    displacement: 3.0,
    cylinders: 6,
    fuelType: 'gasoline',
    aspiration: 'naturally_aspirated',
    stockPower: 231,
    stockTorque: 300,
    redline: 6500,
    revLimit: 6700,
    compressionRatio: 10.2,
    bore: 84.0,
    stroke: 89.6,
    hasVanos: true,
    hasValvetronic: false,
    hasDirectInjection: false,
    ecuType: 'ME9.2',
    dmeFamily: 'MSS54/MSS70',
    supportedMaps: ['stock', 'stage1', 'custom', 'economy', 'valet', 'anti_theft'],
    maxSafePower: 270,
    injectorSizeCc: 360,
    fuelPumpType: 'Bosch in-tank',
    commonIssues: ['Oil filter housing gasket leak', 'Cooling system expansion tank', 'DISA valve', 'VANOS seals', 'CCV valve failure'],
  },
  m57: {
    code: 'm57',
    name: 'M57',
    fullName: 'M57D30TU2 (Turbo Diesel Inline-6)',
    displacement: 3.0,
    cylinders: 6,
    fuelType: 'diesel',
    aspiration: 'single_turbo',
    stockPower: 231,
    stockTorque: 500,
    stockBoost: 1.2,
    redline: 4750,
    revLimit: 5000,
    compressionRatio: 16.5,
    bore: 84.0,
    stroke: 90.0,
    hasVanos: true,
    hasValvetronic: false,
    hasDirectInjection: true,
    ecuType: 'EDC17CP09',
    dmeFamily: 'MSS70',
    supportedMaps: ['stock', 'stage1', 'stage2', 'custom', 'economy'],
    maxSafeBoost: 2.0,
    maxSafePower: 350,
    injectorSizeCc: 420,
    fuelPumpType: 'Bosch CP3 high-pressure',
    commonIssues: ['Swirl flap failure', 'Turbo actuator issues', 'EGR valve carbon buildup', 'Injector seal failure', 'DMF (dual mass flywheel) wear'],
  },
};

export const INJECTOR_DATABASE: Record<string, InjectorSpec> = {
  stock: {
    id: 'stock', name: 'Stock Injectors', brand: 'Bosch', flowRateCc: 630, flowRateLb: 60,
    impedance: 'high', maxDutyCycle: 85, recommendedMaxHp: 85, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54', 'm57'], latencyMs: 1.0, deadTimeMs: 0.85,
    requiresResistorDelete: false,
    notes: 'OEM injectors. Max ~400hp on N54 with E85 mix. Upgrade recommended beyond Stage 1.',
  },
  bosch_550: {
    id: 'bosch_550', name: 'Bosch 550cc', brand: 'Bosch', flowRateCc: 550, flowRateLb: 52.5,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 75, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.95, deadTimeMs: 0.80,
    requiresResistorDelete: false,
    notes: 'Good for NA to mild turbo builds. Supports ~450hp.',
  },
  bosch_650: {
    id: 'bosch_650', name: 'Bosch 650cc', brand: 'Bosch', flowRateCc: 650, flowRateLb: 62,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 90, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.95, deadTimeMs: 0.82,
    requiresResistorDelete: false,
    notes: 'Popular upgrade for Stage 1-2 N54. Supports ~500hp.',
  },
  bosch_750: {
    id: 'bosch_750', name: 'Bosch 750cc', brand: 'Bosch', flowRateCc: 750, flowRateLb: 71.5,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 105, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 1.05, deadTimeMs: 0.90,
    requiresResistorDelete: false,
    notes: 'Stage 2+ N54, full E85 support up to ~550hp.',
  },
  bosch_850: {
    id: 'bosch_850', name: 'Bosch 850cc', brand: 'Bosch', flowRateCc: 850, flowRateLb: 81,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 120, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 1.10, deadTimeMs: 0.95,
    requiresResistorDelete: false,
    notes: 'Stage 2+ with upgraded turbos. ~600hp capable.',
  },
  bosch_1000: {
    id: 'bosch_1000', name: 'Bosch 1000cc', brand: 'Bosch', flowRateCc: 1000, flowRateLb: 95.5,
    impedance: 'low', maxDutyCycle: 93, recommendedMaxHp: 140, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.75, deadTimeMs: 0.60,
    requiresResistorDelete: true,
    notes: 'Low impedance. Requires resistor delete or peak/hold driver. Stage 3 builds.',
  },
  bosch_1200: {
    id: 'bosch_1200', name: 'Bosch 1200cc', brand: 'Bosch', flowRateCc: 1200, flowRateLb: 114.5,
    impedance: 'low', maxDutyCycle: 93, recommendedMaxHp: 170, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.80, deadTimeMs: 0.65,
    requiresResistorDelete: true,
    notes: 'Maximum flow for extreme builds. 700+ hp N54 capable with upgraded fuel system.',
  },
  ev14_550: {
    id: 'ev14_550', name: 'EV14 550cc', brand: 'Bosch EV14', flowRateCc: 550, flowRateLb: 52.5,
    impedance: 'high', maxDutyCycle: 92, recommendedMaxHp: 75, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54', 'm57'], latencyMs: 0.90, deadTimeMs: 0.78,
    requiresResistorDelete: false,
    notes: 'Compact body, great spray pattern. Good for moderate builds.',
  },
  ev14_650: {
    id: 'ev14_650', name: 'EV14 650cc', brand: 'Bosch EV14', flowRateCc: 650, flowRateLb: 62,
    impedance: 'high', maxDutyCycle: 92, recommendedMaxHp: 90, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54', 'm57'], latencyMs: 0.92, deadTimeMs: 0.80,
    requiresResistorDelete: false,
    notes: 'Popular cost-effective upgrade. Supports Stage 1-2 N54.',
  },
  ev14_750: {
    id: 'ev14_750', name: 'EV14 750cc', brand: 'Bosch EV14', flowRateCc: 750, flowRateLb: 71.5,
    impedance: 'high', maxDutyCycle: 92, recommendedMaxHp: 105, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.95, deadTimeMs: 0.82,
    requiresResistorDelete: false,
    notes: 'Best balance of response and flow for most turbo builds.',
  },
  ev14_850: {
    id: 'ev14_850', name: 'EV14 850cc', brand: 'Bosch EV14', flowRateCc: 850, flowRateLb: 81,
    impedance: 'high', maxDutyCycle: 92, recommendedMaxHp: 120, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.98, deadTimeMs: 0.85,
    requiresResistorDelete: false,
    notes: 'Full E85 on Stage 2+ N54 with proper LPFP upgrade.',
  },
  ev14_1000: {
    id: 'ev14_1000', name: 'EV14 1000cc', brand: 'Bosch EV14', flowRateCc: 1000, flowRateLb: 95.5,
    impedance: 'high', maxDutyCycle: 92, recommendedMaxHp: 140, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 1.0, deadTimeMs: 0.88,
    requiresResistorDelete: false,
    notes: 'Top-tier EV14. Supports 600+ hp with excellent idle quality.',
  },
  injector_dynamics_725: {
    id: 'injector_dynamics_725', name: 'ID725', brand: 'Injector Dynamics', flowRateCc: 725, flowRateLb: 69,
    impedance: 'high', maxDutyCycle: 94, recommendedMaxHp: 100, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.85, deadTimeMs: 0.72,
    requiresResistorDelete: false,
    notes: 'Excellent linearity and spray pattern. Great street injector.',
  },
  injector_dynamics_850: {
    id: 'injector_dynamics_850', name: 'ID850', brand: 'Injector Dynamics', flowRateCc: 850, flowRateLb: 81,
    impedance: 'high', maxDutyCycle: 94, recommendedMaxHp: 120, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.88, deadTimeMs: 0.75,
    requiresResistorDelete: false,
    notes: 'Popular choice for 500-550hp N54 builds. OEM-like drivability.',
  },
  injector_dynamics_1000: {
    id: 'injector_dynamics_1000', name: 'ID1000', brand: 'Injector Dynamics', flowRateCc: 1000, flowRateLb: 95.5,
    impedance: 'high', maxDutyCycle: 94, recommendedMaxHp: 140, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.90, deadTimeMs: 0.78,
    requiresResistorDelete: false,
    notes: 'Supports E85 on most turbo builds. Great atomization.',
  },
  injector_dynamics_1300: {
    id: 'injector_dynamics_1300', name: 'ID1300', brand: 'Injector Dynamics', flowRateCc: 1300, flowRateLb: 124,
    impedance: 'high', maxDutyCycle: 94, recommendedMaxHp: 180, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 0.95, deadTimeMs: 0.82,
    requiresResistorDelete: false,
    notes: 'For high boost and E85 builds. 650+ hp capable.',
  },
  injector_dynamics_1700: {
    id: 'injector_dynamics_1700', name: 'ID1700', brand: 'Injector Dynamics', flowRateCc: 1700, flowRateLb: 162,
    impedance: 'high', maxDutyCycle: 94, recommendedMaxHp: 235, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 1.0, deadTimeMs: 0.88,
    requiresResistorDelete: false,
    notes: 'Extreme builds only. 800+ hp with full fuel system. May need idle tuning.',
  },
  siemens_deka_60lb: {
    id: 'siemens_deka_60lb', name: 'Siemens Deka 60lb', brand: 'Siemens Deka', flowRateCc: 630, flowRateLb: 60,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 85, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54', 'm57'], latencyMs: 1.0, deadTimeMs: 0.85,
    requiresResistorDelete: false,
    notes: 'Short body, easy fitment. Budget-friendly option for mild builds.',
  },
  siemens_deka_80lb: {
    id: 'siemens_deka_80lb', name: 'Siemens Deka 80lb', brand: 'Siemens Deka', flowRateCc: 840, flowRateLb: 80,
    impedance: 'high', maxDutyCycle: 90, recommendedMaxHp: 120, pressureRating: 5,
    compatible: ['n54', 'n52', 'm54'], latencyMs: 1.05, deadTimeMs: 0.88,
    requiresResistorDelete: false,
    notes: 'Good for 550-600hp range. Reliable budget performance injector.',
  },
};

export const DME_FLASH_PROTOCOLS: Record<string, DmeFlashProtocol> = {
  msd80: {
    protocolId: 'msd80',
    name: 'MSD80 Flash Protocol',
    description: 'DME flash protocol for N54 MSD80 ECU (2006-2008 pre-LCI)',
    ecuTypes: ['MSD80'],
    flashMethod: 'obd',
    voltageRequired: 13.5,
    signatureRequired: true,
    checksumAlgorithm: 'bmw_custom',
    flashSectors: [
      { name: 'Boot Sector', startAddress: '0x000000', size: 32768, isBootSector: true, writable: false, checksum: '0xCRC' },
      { name: 'Program Flash', startAddress: '0x008000', size: 2097152, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'Data Flash', startAddress: '0x208000', size: 524288, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'EEPROM', startAddress: '0x288000', size: 65536, isBootSector: false, writable: true, checksum: '0xCRC' },
    ],
    safetyChecks: [
      { id: 'battery_voltage', name: 'Battery Voltage', description: 'Verify battery voltage >= 13.5V during flash', checkFunction: 'readBatteryVoltage', critical: true, autoFixable: false },
      { id: 'ignition_on', name: 'Ignition State', description: 'Verify ignition is in KL15 position', checkFunction: 'readIgnitionState', critical: true, autoFixable: false },
      { id: 'engine_off', name: 'Engine Off', description: 'Verify engine is not running', checkFunction: 'readEngineState', critical: true, autoFixable: false },
      { id: 'checksum_verify', name: 'Checksum Verification', description: 'Verify all sector checksums before write', checkFunction: 'verifyChecksums', critical: true, autoFixable: true },
      { id: 'sector_backup', name: 'Sector Backup', description: 'Backup all sectors before modification', checkFunction: 'backupSectors', critical: true, autoFixable: true },
      { id: 'vin_match', name: 'VIN Verification', description: 'Verify VIN in flash matches vehicle', checkFunction: 'verifyVin', critical: false, autoFixable: false },
    ],
    recoveryProcedure: [
      'Connect external 14V power supply',
      'Enter boot mode by grounding pin 24 on DME connector',
      'Flash boot sector recovery image',
      'Flash full factory calibration',
      'Verify with checksum',
    ],
  },
  msd81: {
    protocolId: 'msd81',
    name: 'MSD81 Flash Protocol',
    description: 'DME flash protocol for N54 MSD81 ECU (2008+ LCI)',
    ecuTypes: ['MSD81'],
    flashMethod: 'obd',
    voltageRequired: 13.5,
    signatureRequired: true,
    checksumAlgorithm: 'bmw_custom',
    flashSectors: [
      { name: 'Boot Sector', startAddress: '0x000000', size: 32768, isBootSector: true, writable: false, checksum: '0xCRC' },
      { name: 'Program Flash', startAddress: '0x008000', size: 2097152, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'Data Flash', startAddress: '0x208000', size: 524288, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'EEPROM', startAddress: '0x288000', size: 65536, isBootSector: false, writable: true, checksum: '0xCRC' },
    ],
    safetyChecks: [
      { id: 'battery_voltage', name: 'Battery Voltage', description: 'Verify battery voltage >= 13.5V during flash', checkFunction: 'readBatteryVoltage', critical: true, autoFixable: false },
      { id: 'ignition_on', name: 'Ignition State', description: 'Verify ignition is in KL15 position', checkFunction: 'readIgnitionState', critical: true, autoFixable: false },
      { id: 'engine_off', name: 'Engine Off', description: 'Verify engine is not running', checkFunction: 'readEngineState', critical: true, autoFixable: false },
      { id: 'checksum_verify', name: 'Checksum Verification', description: 'Verify all sector checksums before write', checkFunction: 'verifyChecksums', critical: true, autoFixable: true },
      { id: 'sector_backup', name: 'Sector Backup', description: 'Backup all sectors before modification', checkFunction: 'backupSectors', critical: true, autoFixable: true },
    ],
    recoveryProcedure: [
      'Connect external 14V power supply',
      'Enter boot mode by grounding pin 24 on DME connector',
      'Flash boot sector recovery image',
      'Flash full factory calibration',
    ],
  },
  mev172_n52: {
    protocolId: 'mev172_n52',
    name: 'MEV17.2 N52 Flash Protocol',
    description: 'DME flash protocol for N52 MEV17.2 ECU',
    ecuTypes: ['MEV17.2'],
    flashMethod: 'obd',
    voltageRequired: 13.0,
    signatureRequired: false,
    checksumAlgorithm: 'crc16',
    flashSectors: [
      { name: 'Boot', startAddress: '0x000000', size: 16384, isBootSector: true, writable: false, checksum: '0xCRC' },
      { name: 'Main', startAddress: '0x004000', size: 1048576, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'Config', startAddress: '0x104000', size: 131072, isBootSector: false, writable: true, checksum: '0xCRC' },
    ],
    safetyChecks: [
      { id: 'battery_voltage', name: 'Battery Voltage', description: 'Verify battery >= 13.0V', checkFunction: 'readBatteryVoltage', critical: true, autoFixable: false },
      { id: 'engine_off', name: 'Engine Off', description: 'Engine must be off', checkFunction: 'readEngineState', critical: true, autoFixable: false },
      { id: 'backup', name: 'Full Backup', description: 'Complete backup before flash', checkFunction: 'backupSectors', critical: true, autoFixable: true },
    ],
    recoveryProcedure: [
      'Maintain stable voltage',
      'Reflash factory image via boot mode',
      'Verify checksums',
    ],
  },
  mss70_m54: {
    protocolId: 'mss70_m54',
    name: 'MSS70 M54 Flash Protocol',
    description: 'DME flash protocol for M54 MSS70 ECU',
    ecuTypes: ['MSS70'],
    flashMethod: 'obd',
    voltageRequired: 13.0,
    signatureRequired: false,
    checksumAlgorithm: 'crc16',
    flashSectors: [
      { name: 'Boot', startAddress: '0x000000', size: 16384, isBootSector: true, writable: false, checksum: '0xCRC' },
      { name: 'Main', startAddress: '0x004000', size: 1048576, isBootSector: false, writable: true, checksum: '0xCRC' },
    ],
    safetyChecks: [
      { id: 'battery_voltage', name: 'Battery Voltage', description: 'Verify battery >= 13.0V', checkFunction: 'readBatteryVoltage', critical: true, autoFixable: false },
      { id: 'engine_off', name: 'Engine Off', description: 'Engine must be off', checkFunction: 'readEngineState', critical: true, autoFixable: false },
    ],
    recoveryProcedure: [
      'Connect stable power',
      'Reflash via OBD or bench',
    ],
  },
  edc17_m57: {
    protocolId: 'edc17_m57',
    name: 'EDC17CP09 M57 Flash Protocol',
    description: 'DME flash protocol for M57 EDC17CP09 ECU',
    ecuTypes: ['EDC17CP09'],
    flashMethod: 'obd',
    voltageRequired: 13.5,
    signatureRequired: true,
    checksumAlgorithm: 'crc32',
    flashSectors: [
      { name: 'Boot', startAddress: '0x000000', size: 32768, isBootSector: true, writable: false, checksum: '0xCRC' },
      { name: 'CBOOT', startAddress: '0x008000', size: 65536, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'Code', startAddress: '0x018000', size: 1572864, isBootSector: false, writable: true, checksum: '0xCRC' },
      { name: 'Data', startAddress: '0x198000', size: 524288, isBootSector: false, writable: true, checksum: '0xCRC' },
    ],
    safetyChecks: [
      { id: 'battery_voltage', name: 'Battery Voltage', description: 'Verify >= 13.5V', checkFunction: 'readBatteryVoltage', critical: true, autoFixable: false },
      { id: 'ignition', name: 'Ignition On', description: 'KL15 must be on', checkFunction: 'readIgnitionState', critical: true, autoFixable: false },
      { id: 'checksum', name: 'CRC32 Check', description: 'Verify CRC32 before write', checkFunction: 'verifyChecksums', critical: true, autoFixable: true },
      { id: 'backup', name: 'Full Backup', description: 'Complete ECU backup', checkFunction: 'backupSectors', critical: true, autoFixable: true },
    ],
    recoveryProcedure: [
      'Connect bench power',
      'Use BDM/JTAG if OBD fails',
      'Flash complete factory image',
    ],
  },
};

export function getInjectorsForEngine(engine: string): InjectorSpec[] {
  return Object.values(INJECTOR_DATABASE).filter(i => i.compatible.includes(engine as any));
}

export function getProtocolForEcu(ecuType: string): DmeFlashProtocol | undefined {
  return Object.values(DME_FLASH_PROTOCOLS).find(p => p.ecuTypes.includes(ecuType));
}

export function calculateMaxHp(injectorCc: number, dutyCycle: number, numCylinders: number, fuelType: 'gasoline' | 'diesel' = 'gasoline'): number {
  const bsfc = fuelType === 'gasoline' ? 0.55 : 0.45; // brake specific fuel consumption
  const maxFlowPerInjector = injectorCc * (dutyCycle / 100);
  const totalFlow = maxFlowPerInjector * numCylinders;
  return Math.round(totalFlow / (bsfc * 6.3));
}

export function calculateRequiredInjectorCc(targetHp: number, numCylinders: number, dutyCycle: number = 85, fuelType: 'gasoline' | 'diesel' = 'gasoline'): number {
  const bsfc = fuelType === 'gasoline' ? 0.55 : 0.45;
  const totalFlowNeeded = targetHp * bsfc * 6.3;
  const perInjector = totalFlowNeeded / numCylinders;
  return Math.ceil(perInjector / (dutyCycle / 100));
}
